# https://mlflow.org

mlflow:
  _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
  experiment_name: ${name}
  tracking_uri: null
  tags: null
  save_dir: ${original_work_dir}/logs/mlruns
  prefix: ""
  artifact_location: null
